// Generated by LiveScript 1.3.1
(function(){
  var WebTorrent, client, hash;
  WebTorrent = require('webtorrent');
  client = new WebTorrent();
  hash = 'da40fb70e29f1fc659cd21848ff7d431ff48feb8';
  client.add(hash, function(torrent){
    console.log(torrent);
  });
}).call(this);
